services:
  - type: web
    name: fraudradar
    env: node
    buildCommand: |
      npm install --prefix backend
      npm install --prefix frontend
      npm run build --prefix frontend -- --configuration production
    startCommand: "node backend/src/server.js"
